version: "2"

services:
  registry:
    image: registry:latest
    ports:
      - 5000:5000
    volumes:
      - ./volumes/registry:/var/lib/registry
    restart: always

  ui:
    build: .
    ports:
      - 8080:8080
    restart: always
    environment:
      REGISTRY: registry:5000
    volumes:
      - ./volumes/ui/docker:/var/lib/docker
    privileged: true